### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/News_Parser_bot#2]
например, my_parser, my_plot, res
что за парсер, график, результат?

**Comment by kuzmichevdima** [comment]
my_bot

**Comment by kuzmichevdima** [comment]
https://github.com/ZyryanovI/News_Parser_bot/blob/6a7c1d51c04d11cb2f4261ac5fc50613ee49ef02/my_bot.py#L228-L229

plot_f, plot_l - что это за графики?

**Comment by ZyryanovI** [comment]
исправил
