### ISSUE TITLE
копипаст

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/News_Parser_bot#3]
https://github.com/ZyryanovI/News_Parser_bot/blob/6a7c1d51c04d11cb2f4261ac5fc50613ee49ef02/my_bot.py#L108-L117

https://github.com/ZyryanovI/News_Parser_bot/blob/6a7c1d51c04d11cb2f4261ac5fc50613ee49ef02/my_bot.py#L137-L144

такого типа реплики бота нужно вынести в строковые константы

**Comment by kuzmichevdima** [comment]
https://github.com/ZyryanovI/News_Parser_bot/blob/6a7c1d51c04d11cb2f4261ac5fc50613ee49ef02/my_bot.py#L199

https://github.com/ZyryanovI/News_Parser_bot/blob/6a7c1d51c04d11cb2f4261ac5fc50613ee49ef02/my_bot.py#L221

вот эти две функции очень похожи

**Comment by ZyryanovI** [comment]
исправил
